version: '3'

services:
  httpbin:
    image: kennethreitz/httpbin
    ports:
      - "8080:80"

  pytest:
    image: python:3.9
    user: "tester"
    volumes:
      - ./results:/results
      - ./pytests:/pytests
    depends_on:
      - httpbin
    command: pytest /pytests --junitxml=/results/report.xml
