version: '3'

services:
  httpbin:
    image: kennethreitz/httpbin
    ports:
      - "8080:80"

  pytest:
    image: python:3.9
    volumes:
      - ./results:/results
      - ./pytests:/pytests
    depends_on:
      - httpbin
    command: /bin/sh -c "pip install pytest requests && pytest /pytests --junitxml=/results/report.xml"
